/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test1;
import weka.classifiers.*;
import weka.classifiers.trees.*;
import test1.alogrithm.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	J48 j48_classifier=new J48();
	J48Classifier test=new 	J48Classifier();

	String file_name="./iris.arff";
	test.getFile(file_name);
    }
}
